// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_SqdXMlog25BuUbnVKyEskcChQ9vA9sk',
    appId: '1:1027880112915:web:c6c470960a95ffc5be00e6',
    messagingSenderId: '1027880112915',
    projectId: 'zoomclone-d19e6',
    authDomain: 'zoomclone-d19e6.firebaseapp.com',
    storageBucket: 'zoomclone-d19e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQu9RGE9hrSq_2OwFoZvLMYF85rqTnjTg',
    appId: '1:1027880112915:android:c25a15903322e52abe00e6',
    messagingSenderId: '1027880112915',
    projectId: 'zoomclone-d19e6',
    storageBucket: 'zoomclone-d19e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8F6ayVeftYymFVshEiYc8d9d_Cn8veTY',
    appId: '1:1027880112915:ios:6e513834475f252bbe00e6',
    messagingSenderId: '1027880112915',
    projectId: 'zoomclone-d19e6',
    storageBucket: 'zoomclone-d19e6.appspot.com',
    iosBundleId: 'com.example.zoom',
  );
}
