// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxooO1oW9f0_Y5oWicYYNG8ONACroIMjk',
    appId: '1:802632551195:web:ecd7690cb20c20c54b61be',
    messagingSenderId: '802632551195',
    projectId: 'zoom-clone-26c89',
    authDomain: 'zoom-clone-26c89.firebaseapp.com',
    storageBucket: 'zoom-clone-26c89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4XwQDmmkRgQveS-W1JrE6mcEsb38fmM',
    appId: '1:802632551195:android:c36def87b22bfbeb4b61be',
    messagingSenderId: '802632551195',
    projectId: 'zoom-clone-26c89',
    storageBucket: 'zoom-clone-26c89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjXRJ8coRW0qsT--aykBATirJApvQZAYA',
    appId: '1:802632551195:ios:4dc9ef66f13ddb2c4b61be',
    messagingSenderId: '802632551195',
    projectId: 'zoom-clone-26c89',
    storageBucket: 'zoom-clone-26c89.appspot.com',
    iosBundleId: 'com.example.zoom',
  );
}
